### ISSUE TITLE
rufus.akeo.ie and rufus.ie are currently down

### ISSUE THREAD

**Issue by Septarius** [pbatard/rufus-web#2]
It is not responding as of the writing of this issue. I checked a couple of down detectors so I believe it is not just me.
Figured this would be the best way to alert you.

P.S. Rufus is awesome!

**Comment by pbatard** [comment]
Yes. We are being subjected to coordinated DDoS attacks (Can you imagine that there's some low life idiot out there who thinks that providing a free utility should be punished? How much of a loser does that person have to be...). 

We are working to sort something out but it may take a little while to get some of the content back.
