### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by Mynacol** [pbatard/rufus-web#20]
Hi,
I'm using Rufus for years and just noticed that it's open source 🙈 and the web page is hosted on GitHub.

I noticed the domain rufus.ie is missing AAAA DNS Resource Records, so IPv6 is not available.
GitHub has added [IPv6 support](https://github.blog/changelog/2021-09-30-enabling-ipv6-support-for-github-pages/) for GitHub Pages some time ago and I would appreciate you adding a AAAA DNS entry.

Usually, GitHub Pages only has static content, so you would not be able to somehow interpret the client's IP address and expect it to have a IPv4 form, but then I have seen a PHP script in this repo. So please check if you somehow process the remote IP addresses (I doubt it) and add IPv6 support.

Thanks

**Comment by pbatard** [comment]
> but then I have seen a PHP script in this repo.

Which is only used to generate the static pages locally, that can then be committed to GitHub.

I have just added the AAAA DNS entries so I will close that issue.

**Comment by Mynacol** [comment]
Thanks, I appreciate it.
