### ISSUE TITLE
About Japanese Translations Contributor

### ISSUE THREAD

**Issue by mkaraki** [pbatard/rufus-web#4]
Japanese Page (ja_JP.html)'s Contributor "唐澤 貴洋" is name of Japanese lawyer.
I don't know it's contributor's actual name, But If it's not actual name, IT SHOULD BE DELETE.

唐澤 貴洋 is lawyer and he got a lot of Killing notice and In the past, there was also a notice of a blast in his name.

So. In Japan, "唐澤 貴洋" is very bad name.
If you (or contributor) uses it for joke. YOU SHOULD REMOVE THAT.
And If it's actual name, You should change to the nickname or write It does not matter.

And Finally, "唐澤 貴洋" is very bad name to use in joke. Please fix this big problem.

Thanks.

**Comment by pbatard** [comment]
Should be fixed bow. Thanks for the report.
